# Generated by Django 4.2.23 on 2025-10-30 04:41

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heavy_equipment', '0005_delete_heavyequipmentpowergeneration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerAsset',
            fields=[
                ('heavyequipmentasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='heavy_equipment.heavyequipmentasset')),
                ('power_asset_type', models.CharField(choices=[('generator', 'Generator'), ('light_tower', 'Light tower'), ('battery', 'Battery or solar pack'), ('pump', 'Pump / auxiliary power')], default='generator', max_length=32)),
                ('max_output_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='rated output (kW)')),
                ('supports_three_phase', models.BooleanField(default=False)),
                ('fuel_burn_rate_lph', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated fuel burn rate (L/h) at nominal load.', max_digits=10, null=True)),
                ('last_runtime_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Runtime hours recorded at last service.', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Power & lighting asset',
                'verbose_name_plural': 'Power & lighting assets',
            },
            bases=('heavy_equipment.heavyequipmentasset',),
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
