# Generated by Django 4.2.23 on 2025-10-30 04:41

from django.db import migrations


POWER_TYPE_MAP = {
    "generator": "generator",
    "light_tower": "light_tower",
    "pump": "pump",
}


def create_power_records(apps, schema_editor):
    HeavyEquipmentAsset = apps.get_model("heavy_equipment", "HeavyEquipmentAsset")
    PowerAsset = apps.get_model("power", "PowerAsset")

    power_manager = PowerAsset._base_manager
    existing_ids = set(
        power_manager.values_list("heavyequipmentasset_ptr_id", flat=True)
    )
    candidates = HeavyEquipmentAsset._base_manager.filter(
        equipment_type__in=POWER_TYPE_MAP.keys()
    )
    bulk = []
    for asset in candidates:
        if asset.pk in existing_ids:
            continue
        power_type = POWER_TYPE_MAP.get(asset.equipment_type, "generator")
        bulk.append(
            PowerAsset(
                heavyequipmentasset_ptr_id=asset.pk,
                power_asset_type=power_type,
            )
        )
    if bulk:
            power_manager.bulk_create(bulk, ignore_conflicts=True)


def remove_power_records(apps, schema_editor):
    PowerAsset = apps.get_model("power", "PowerAsset")
    PowerAsset._base_manager.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("power", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_power_records, remove_power_records),
    ]
