# Generated by Django 4.2.23 on 2025-10-28 16:58

from django.db import migrations
import django.db.models.manager
import ralph.lib.transitions.fields

from ralph.lib.transitions.migration import TransitionActionMigration


def _get_actions(content_type, action_names, ActionModel):
    actions = []
    for action_name in action_names:
        action, _ = ActionModel.objects.get_or_create(name=action_name)
        action.content_type.add(content_type)
        actions.append(action)
    return actions


def create_heavy_equipment_transitions(apps, schema_editor):
    from ralph.heavy_equipment.models import HeavyEquipmentAsset, HeavyEquipmentAssetStatus

    Transition = apps.get_model("transitions", "Transition")
    TransitionModel = apps.get_model("transitions", "TransitionModel")
    Action = apps.get_model("transitions", "Action")

    from django.contrib.contenttypes.models import ContentType as DjangoContentType

    ContentTypeModel = apps.get_model("contenttypes", "ContentType")
    ct_id = DjangoContentType.objects.get_for_model(HeavyEquipmentAsset).pk
    content_type = ContentTypeModel.objects.get(pk=ct_id)
    transition_model, _ = TransitionModel.objects.get_or_create(
        content_type=content_type,
        field_name="status",
    )

    transitions = [
        (
            "Activate asset",
            [HeavyEquipmentAssetStatus.new.id, HeavyEquipmentAssetStatus.standby.id],
            HeavyEquipmentAssetStatus.active.id,
            ["activate_heavy_equipment_asset"],
        ),
        (
            "Stand down asset",
            [HeavyEquipmentAssetStatus.active.id],
            HeavyEquipmentAssetStatus.standby.id,
            ["stand_down_heavy_equipment"],
        ),
        (
            "Begin maintenance",
            [HeavyEquipmentAssetStatus.active.id, HeavyEquipmentAssetStatus.damaged.id],
            HeavyEquipmentAssetStatus.under_maintenance.id,
            ["start_heavy_equipment_maintenance"],
        ),
        (
            "Complete maintenance",
            [HeavyEquipmentAssetStatus.under_maintenance.id],
            HeavyEquipmentAssetStatus.active.id,
            ["complete_heavy_equipment_maintenance"],
        ),
        (
            "Report damage",
            [HeavyEquipmentAssetStatus.active.id],
            HeavyEquipmentAssetStatus.damaged.id,
            ["report_heavy_equipment_damage"],
        ),
        (
            "Retire asset",
            [
                HeavyEquipmentAssetStatus.new.id,
                HeavyEquipmentAssetStatus.standby.id,
                HeavyEquipmentAssetStatus.active.id,
                HeavyEquipmentAssetStatus.under_maintenance.id,
                HeavyEquipmentAssetStatus.damaged.id,
            ],
            HeavyEquipmentAssetStatus.retired.id,
            ["retire_heavy_equipment_asset"],
        ),
        (
            "Log refuel",
            [HeavyEquipmentAssetStatus.active.id],
            HeavyEquipmentAssetStatus.active.id,
            ["log_heavy_equipment_refuel"],
        ),
    ]

    for name, source, target, action_names in transitions:
        transition, _ = Transition.objects.update_or_create(
            model=transition_model,
            name=name,
            defaults={
                "source": source,
                "target": str(target),
                "run_asynchronously": False,
                "async_service_name": None,
            },
        )
        actions = _get_actions(content_type, action_names, Action)
        transition.actions.set(actions)


def remove_heavy_equipment_transitions(apps, schema_editor):
    from ralph.heavy_equipment.models import HeavyEquipmentAsset

    Transition = apps.get_model("transitions", "Transition")
    TransitionModel = apps.get_model("transitions", "TransitionModel")

    from django.contrib.contenttypes.models import ContentType as DjangoContentType

    ContentTypeModel = apps.get_model("contenttypes", "ContentType")
    ct_id = DjangoContentType.objects.get_for_model(HeavyEquipmentAsset).pk
    content_type = ContentTypeModel.objects.get(pk=ct_id)
    try:
        transition_model = TransitionModel.objects.get(
            content_type=content_type,
            field_name="status",
        )
    except TransitionModel.DoesNotExist:
        return

    Transition.objects.filter(
        model=transition_model,
        name__in=[
            "Activate asset",
            "Stand down asset",
            "Begin maintenance",
            "Complete maintenance",
            "Report damage",
            "Retire asset",
            "Log refuel",
        ],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('heavy_equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='heavyequipmentasset',
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='heavyequipmentasset',
            name='status',
            field=ralph.lib.transitions.fields.TransitionField(choices=[(1, 'new'), (2, 'standby'), (3, 'active'), (4, 'under maintenance'), (5, 'damaged'), (6, 'retired')], default=1),
        ),
        TransitionActionMigration(),
        migrations.RunPython(create_heavy_equipment_transitions, remove_heavy_equipment_transitions),
    ]
