# Generated by Django 4.2.23 on 2025-10-28 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heavy_equipment', '0002_alter_heavyequipmentasset_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heavyequipmentasset',
            name='battery_level_threshold_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='battery level threshold (%)'),
        ),
        migrations.AddField(
            model_name='heavyequipmentasset',
            name='fuel_level_threshold_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='fuel level threshold (%)'),
        ),
        migrations.AddField(
            model_name='heavyequipmentasset',
            name='water_level_threshold_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='water level threshold (%)'),
        ),
    ]
