# Generated by Django 4.2.23 on 2025-10-29 18:11

import django.core.validators
from django.db import migrations, models
import django.db.models.manager
import ralph.heavy_equipment.models


class Migration(migrations.Migration):

    dependencies = [
        ('heavy_equipment', '0003_heavyequipmentasset_battery_level_threshold_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeavyEquipmentDebrisRemoval',
            fields=[
            ],
            options={
                'verbose_name': 'Debris removal equipment',
                'verbose_name_plural': 'Debris removal equipment',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ralph.heavy_equipment.models.HeavyEquipmentGroupProxyMixin, 'heavy_equipment.heavyequipmentasset'),
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HeavyEquipmentMaterialHandling',
            fields=[
            ],
            options={
                'verbose_name': 'Material handling equipment',
                'verbose_name_plural': 'Material handling equipment',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ralph.heavy_equipment.models.HeavyEquipmentGroupProxyMixin, 'heavy_equipment.heavyequipmentasset'),
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HeavyEquipmentPowerGeneration',
            fields=[
            ],
            options={
                'verbose_name': 'Power generation & lighting',
                'verbose_name_plural': 'Power generation & lighting',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ralph.heavy_equipment.models.HeavyEquipmentGroupProxyMixin, 'heavy_equipment.heavyequipmentasset'),
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HeavyEquipmentWaterManagement',
            fields=[
            ],
            options={
                'verbose_name': 'Water & fluid management equipment',
                'verbose_name_plural': 'Water & fluid management equipment',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ralph.heavy_equipment.models.HeavyEquipmentGroupProxyMixin, 'heavy_equipment.heavyequipmentasset'),
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='heavyequipmentasset',
            name='acquired_on',
            field=models.DateField(blank=True, null=True, verbose_name='acquired on'),
        ),
        migrations.AddField(
            model_name='heavyequipmentasset',
            name='acquisition_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='acquisition cost'),
        ),
        migrations.AddField(
            model_name='heavyequipmentasset',
            name='acquisition_vendor',
            field=models.CharField(blank=True, max_length=128, verbose_name='acquisition vendor'),
        ),
        migrations.AddField(
            model_name='heavyequipmentasset',
            name='deployed_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last deployed on'),
        ),
        migrations.AddField(
            model_name='heavyequipmentasset',
            name='deployment_notes',
            field=models.TextField(blank=True, verbose_name='deployment notes'),
        ),
        migrations.AddField(
            model_name='heavyequipmentasset',
            name='deployment_site',
            field=models.CharField(blank=True, max_length=128, verbose_name='deployment site / project'),
        ),
        migrations.AddField(
            model_name='heavyequipmentasset',
            name='deployment_status',
            field=models.CharField(choices=[('staged', 'Staged / ready'), ('deployed', 'Deployed / on-site'), ('returning', 'Returning / demobilizing'), ('stored', 'Stored / warehouse')], default='staged', max_length=16, verbose_name='deployment status'),
        ),
        migrations.AddField(
            model_name='heavyequipmentasset',
            name='hydraulic_oil_capacity_liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='hydraulic oil capacity (L)'),
        ),
        migrations.AddField(
            model_name='heavyequipmentasset',
            name='hydraulic_oil_level_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='hydraulic oil level (%)'),
        ),
        migrations.AddField(
            model_name='heavyequipmentasset',
            name='lease_expiration',
            field=models.DateField(blank=True, null=True, verbose_name='lease expiration'),
        ),
        migrations.AddField(
            model_name='heavyequipmentasset',
            name='ownership_type',
            field=models.CharField(choices=[('owned', 'Owned'), ('leased', 'Leased'), ('rented', 'Rented'), ('borrowed', 'Borrowed / mutual aid')], default='owned', max_length=16, verbose_name='ownership type'),
        ),
        migrations.AddField(
            model_name='heavyequipmentasset',
            name='power_output_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='power output (kW)'),
        ),
        migrations.AddField(
            model_name='heavyequipmentasset',
            name='warranty_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='warranty expiry'),
        ),
        migrations.AddField(
            model_name='heavyequipmentasset',
            name='waste_level_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='waste level (%)'),
        ),
        migrations.AddField(
            model_name='heavyequipmentasset',
            name='waste_tank_capacity_liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='waste tank capacity (L)'),
        ),
        migrations.AlterField(
            model_name='heavyequipmentasset',
            name='equipment_type',
            field=models.CharField(choices=[('generator', 'Generator'), ('trailer', 'Trailer'), ('excavator', 'Excavator'), ('bulldozer', 'Bulldozer'), ('loader', 'Loader / Skid steer'), ('pump', 'Pump'), ('tank', 'Tank / Water system'), ('crane', 'Crane'), ('forklift', 'Forklift or telehandler'), ('light_tower', 'Light tower'), ('other', 'Other')], default='other', max_length=32, verbose_name='equipment type'),
        ),
    ]
