# Generated by Django 4.2.23 on 2025-10-31

from django.db import migrations


POWER_TYPES = {"generator", "light_tower", "pump"}
TRAILER_TYPES = {"trailer", "tank"}


def forward_update_content_types(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    BaseObject = apps.get_model("assets", "BaseObject")
    HeavyEquipmentAsset = apps.get_model("heavy_equipment", "HeavyEquipmentAsset")
    TrailerAsset = apps.get_model("trailers", "TrailerAsset")
    PowerAsset = apps.get_model("power", "PowerAsset")

    ct_trailer = ContentType.objects.get_by_natural_key("trailers", "trailerasset")
    ct_power = ContentType.objects.get_by_natural_key("power", "powerasset")

    # Ensure child rows exist (idempotent if created by previous migrations)
    existing_trailer_ids = set(
        TrailerAsset._base_manager.values_list("heavyequipmentasset_ptr_id", flat=True)
    )
    existing_power_ids = set(
        PowerAsset._base_manager.values_list("heavyequipmentasset_ptr_id", flat=True)
    )

    trailer_candidates = list(
        HeavyEquipmentAsset._base_manager.filter(equipment_type__in=TRAILER_TYPES)
        .values_list("pk", "equipment_type")
    )
    power_candidates = list(
        HeavyEquipmentAsset._base_manager.filter(equipment_type__in=POWER_TYPES)
        .values_list("pk", "equipment_type")
    )

    # Create missing child rows
    trailer_bulk = []
    for pk, etype in trailer_candidates:
        if pk in existing_trailer_ids:
            continue
        subtype = "water" if etype == "tank" else "specialty"
        trailer_bulk.append(TrailerAsset(heavyequipmentasset_ptr_id=pk, trailer_subtype=subtype))
    if trailer_bulk:
        TrailerAsset._base_manager.bulk_create(trailer_bulk, ignore_conflicts=True)

    power_bulk = []
    for pk, etype in power_candidates:
        if pk in existing_power_ids:
            continue
        if etype not in {"generator", "light_tower", "pump"}:
            continue
        power_type = etype
        power_bulk.append(PowerAsset(heavyequipmentasset_ptr_id=pk, power_asset_type=power_type))
    if power_bulk:
        PowerAsset._base_manager.bulk_create(power_bulk, ignore_conflicts=True)

    # Update BaseObject.content_type so polymorphism resolves to subclass
    trailer_ids = [pk for pk, _ in trailer_candidates]
    power_ids = [pk for pk, _ in power_candidates]
    if trailer_ids:
        BaseObject.objects.filter(pk__in=trailer_ids).update(content_type_id=ct_trailer.id)
    if power_ids:
        BaseObject.objects.filter(pk__in=power_ids).update(content_type_id=ct_power.id)


def reverse_update_content_types(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    BaseObject = apps.get_model("assets", "BaseObject")
    HeavyEquipmentAsset = apps.get_model("heavy_equipment", "HeavyEquipmentAsset")
    TrailerAsset = apps.get_model("trailers", "TrailerAsset")
    PowerAsset = apps.get_model("power", "PowerAsset")

    ct_he = ContentType.objects.get_by_natural_key(
        "heavy_equipment", "heavyequipmentasset"
    )

    # Determine currently classified ids
    trailer_ids = list(
        TrailerAsset._base_manager.values_list("heavyequipmentasset_ptr_id", flat=True)
    )
    power_ids = list(
        PowerAsset._base_manager.values_list("heavyequipmentasset_ptr_id", flat=True)
    )

    # Reset BaseObject content_type back to heavy_equipment
    if trailer_ids:
        BaseObject.objects.filter(pk__in=trailer_ids).update(content_type_id=ct_he.id)
    if power_ids:
        BaseObject.objects.filter(pk__in=power_ids).update(content_type_id=ct_he.id)

    # Optionally remove child rows (safe because parent remains)
    TrailerAsset._base_manager.all().delete()
    PowerAsset._base_manager.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("heavy_equipment", "0005_delete_heavyequipmentpowergeneration_and_more"),
        ("trailers", "0002_reclassify_trailers"),
        ("power", "0002_reclassify_power_assets"),
        ("assets", "0052_compliance_template_and_reportconfig"),
    ]

    operations = [
        migrations.RunPython(forward_update_content_types, reverse_update_content_types),
    ]

