# Generated by Django 4.2.23 on 2025-10-12

from django.db import migrations, models


def create_disaster_relief_categories(apps, schema_editor):
    Category = apps.get_model("assets", "Category")
    if Category.objects.filter(name="Disaster Relief", parent__isnull=True).exists():
        return

    max_tree_id = Category.objects.aggregate(models.Max("tree_id"))["tree_id__max"] or 0
    tree_id = max_tree_id + 1

    children = [
        ("DRTR", "Trailers"),
        ("DRVE", "Vehicles"),
        ("DRHE", "Heavy Equipment"),
    ]

    root = Category.objects.create(
        name="Disaster Relief",
        code="DR",
        parent=None,
        tree_id=tree_id,
        lft=1,
        rght=2 * (len(children) + 1),
        level=0,
    )

    for index, (code, name) in enumerate(children):
        left = 2 * index + 2
        right = left + 1
        Category.objects.create(
            name=name,
            code=code,
            parent=root,
            tree_id=tree_id,
            lft=left,
            rght=right,
            level=1,
        )


def remove_disaster_relief_categories(apps, schema_editor):
    Category = apps.get_model("assets", "Category")
    try:
        root = Category.objects.get(name="Disaster Relief", parent__isnull=True)
    except Category.DoesNotExist:
        return
    Category.objects.filter(parent=root, name__in=["Trailers", "Vehicles", "Heavy Equipment"]).delete()
    root.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0042_alter_configurationmodule_unique_together_and_more"),
    ]

    operations = [
        migrations.RunPython(
            create_disaster_relief_categories,
            remove_disaster_relief_categories,
        ),
    ]
