# Generated by Django 4.2.23 on 2025-10-28 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ralph.lib.mixins.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0043_disaster_relief_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'back office'), (2, 'data center'), (3, 'part'), (4, 'all'), (5, 'fleet'), (6, 'drone'), (7, 'sensor'), (8, 'heavy equipment')], verbose_name='type'),
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('record_type', models.PositiveIntegerField(choices=[(1, 'maintenance'), (2, 'repair'), (3, 'refuel'), (4, 'calibration'), (5, 'inspection'), (6, 'other')], default=1)),
                ('status', models.PositiveIntegerField(choices=[(1, 'open'), (2, 'in progress'), (3, 'completed')], default=1)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_completion', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('out_of_service', models.BooleanField(default=False)),
                ('performed_by', models.CharField(blank=True, max_length=128)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('base_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='assets.baseobject')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_maintenance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance record',
                'verbose_name_plural': 'Maintenance records',
                'ordering': ('-opened_at', '-pk'),
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
    ]
