# Generated by Django 4.2.23 on 2025-10-29 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ralph.lib.mixins.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20250408_1522'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0044_alter_assetmodel_type_maintenancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('source', models.CharField(help_text='Origin of the reading (device, system, integration).', max_length=64)),
                ('metric', models.CharField(help_text='Name of the metric, e.g. fuel_level, temperature, altitude.', max_length=64)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('value_text', models.CharField(blank=True, max_length=256)),
                ('captured_at', models.DateTimeField(blank=True, help_text='Timestamp when the measurement was captured on the device.', null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('base_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_readings', to='assets.baseobject')),
            ],
            options={
                'verbose_name': 'Telemetry reading',
                'verbose_name_plural': 'Telemetry readings',
                'ordering': ('-captured_at', '-ingested_at'),
                'indexes': [models.Index(fields=['base_object', 'metric', 'captured_at'], name='assets_tele_base_ob_563494_idx'), models.Index(fields=['metric'], name='assets_tele_metric_ce2f84_idx')],
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DeploymentEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('status', models.PositiveIntegerField(choices=[(1, 'deployed / in use'), (2, 'in transit'), (3, 'maintenance'), (4, 'storage / standby'), (5, 'retired')], default=1)),
                ('location', models.CharField(blank=True, help_text='Human readable deployment location (site, depot, project).', max_length=128)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_deployments', to='accounts.team')),
                ('assigned_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_assignments', to=settings.AUTH_USER_MODEL)),
                ('base_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_entries', to='assets.baseobject')),
            ],
            options={
                'verbose_name': 'Deployment entry',
                'verbose_name_plural': 'Deployment entries',
                'ordering': ('-started_at', '-pk'),
                'indexes': [models.Index(fields=['base_object', 'started_at'], name='assets_depl_base_ob_7090fc_idx'), models.Index(fields=['status'], name='assets_depl_status_e2fe18_idx')],
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('record_type', models.PositiveIntegerField(choices=[(1, 'inspection'), (2, 'certification'), (3, 'permit'), (4, 'registration'), (5, 'insurance'), (6, 'calibration'), (7, 'other')], default=1)),
                ('status', models.PositiveIntegerField(choices=[(1, 'compliant'), (2, 'due soon'), (3, 'overdue'), (4, 'failed')], default=1)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('performed_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('performed_by', models.CharField(blank=True, max_length=128)),
                ('reference', models.CharField(blank=True, help_text='External ticket, certificate or permit reference.', max_length=128)),
                ('document_url', models.URLField(blank=True, help_text='Link to compliance document or evidence.')),
                ('notes', models.TextField(blank=True)),
                ('base_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='assets.baseobject')),
            ],
            options={
                'verbose_name': 'Compliance record',
                'verbose_name_plural': 'Compliance records',
                'ordering': ('expires_on', 'title'),
                'indexes': [models.Index(fields=['base_object', 'expires_on'], name='assets_comp_base_ob_3a3c7d_idx')],
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
    ]
