# Generated by Django 4.2.23 on 2025-10-29 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ralph.lib.mixins.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('assets', '0045_telemetryreading_deploymententry_compliancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('status', models.PositiveIntegerField(choices=[(1, 'pending'), (2, 'in progress'), (3, 'completed')], default=1)),
                ('method', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, help_text='Upload sale receipts or certificates of destruction.', null=True, upload_to='disposal_documents/%Y/%m/')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_disposals', to=settings.AUTH_USER_MODEL)),
                ('base_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disposal_record', to='assets.baseobject')),
            ],
            options={
                'verbose_name': 'Disposal record',
                'verbose_name_plural': 'Disposal records',
                'ordering': ('-created',),
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DisposalTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Limit disposal template to a specific asset type.', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Disposal template',
                'verbose_name_plural': 'Disposal templates',
                'ordering': ('name',),
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='document',
            field=models.FileField(blank=True, help_text='Upload inspection certificates or permits.', null=True, upload_to='compliance_documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_maintenance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='closure_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='closure_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='closure_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='service_provider',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='record_type',
            field=models.PositiveIntegerField(choices=[(1, 'maintenance'), (2, 'repair'), (3, 'refuel'), (4, 'calibration'), (5, 'inspection'), (6, 'approval'), (7, 'other')], default=1),
        ),
        migrations.CreateModel(
            name='DisposalTemplateTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('name', models.CharField(max_length=128)),
                ('is_required', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='assets.disposaltemplate')),
            ],
            options={
                'verbose_name': 'Disposal template task',
                'verbose_name_plural': 'Disposal template tasks',
                'ordering': ('template', 'name'),
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DisposalTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('name', models.CharField(max_length=128)),
                ('is_required', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_disposal_tasks', to=settings.AUTH_USER_MODEL)),
                ('disposal_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='assets.disposalrecord')),
            ],
            options={
                'verbose_name': 'Disposal task',
                'verbose_name_plural': 'Disposal tasks',
                'ordering': ('disposal_record', 'name'),
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.AddField(
            model_name='disposalrecord',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.disposaltemplate'),
        ),
        migrations.CreateModel(
            name='ComplianceTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('name', models.CharField(max_length=128)),
                ('record_type', models.PositiveIntegerField(choices=[(1, 'inspection'), (2, 'certification'), (3, 'permit'), (4, 'registration'), (5, 'insurance'), (6, 'calibration'), (7, 'other')], default=1)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('frequency_days', models.PositiveIntegerField(blank=True, help_text='Number of days between required checks.', null=True)),
                ('grace_period_days', models.PositiveIntegerField(default=0, help_text='Grace period before the compliance item is considered overdue.')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_create', models.BooleanField(default=True, help_text='Automatically create compliance records for matching assets.')),
                ('content_type', models.ForeignKey(blank=True, help_text='Limit template to a specific asset type.', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Compliance template',
                'verbose_name_plural': 'Compliance templates',
                'ordering': ('name',),
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_records', to='assets.compliancetemplate'),
        ),
    ]
