# Generated by Django 4.2.23 on 2025-10-29 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ralph.lib.mixins.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0046_disposalrecord_disposaltemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymententry',
            name='current_speed_kmh',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Latest reported speed while this deployment is active.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='deploymententry',
            name='handover_notes',
            field=models.TextField(blank=True, help_text='Notes captured during the last handoff.'),
        ),
        migrations.AddField(
            model_name='deploymententry',
            name='last_telemetry_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last telemetry update tied to this deployment.', null=True),
        ),
        migrations.AddField(
            model_name='deploymententry',
            name='shift_end',
            field=models.DateTimeField(blank=True, help_text='Scheduled end of the duty shift.', null=True),
        ),
        migrations.AddField(
            model_name='deploymententry',
            name='shift_label',
            field=models.CharField(blank=True, help_text='Roster or shift label (e.g. Day, Night, Alpha).', max_length=64),
        ),
        migrations.AddField(
            model_name='deploymententry',
            name='shift_start',
            field=models.DateTimeField(blank=True, help_text='Scheduled start of the duty shift.', null=True),
        ),
        migrations.AddField(
            model_name='telemetryreading',
            name='deployment_entry',
            field=models.ForeignKey(blank=True, help_text='Deployment assignment active when this reading was captured.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry_events', to='assets.deploymententry'),
        ),
        migrations.CreateModel(
            name='DeploymentAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('role', models.CharField(blank=True, help_text='Role of the person on this deployment (e.g. Operator, Driver).', max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('handover_notes', models.TextField(blank=True)),
                ('last_reported_at', models.DateTimeField(blank=True, null=True)),
                ('last_reported_metric', models.CharField(blank=True, max_length=64)),
                ('deployment_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.deploymententry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_deployment_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deployment assignment',
                'verbose_name_plural': 'Deployment assignments',
                'ordering': ('-started_at', '-pk'),
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
    ]
