# Generated by Django 4.2.23 on 2025-10-29 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ralph.lib.mixins.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('assets', '0047_deploymententry_current_speed_kmh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('severity', models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Open'), (2, 'In progress'), (3, 'Resolved')], default=1)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_asset_incidents', to=settings.AUTH_USER_MODEL)),
                ('base_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='assets.baseobject')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_asset_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset incident',
                'verbose_name_plural': 'Asset incidents',
                'ordering': ('-opened_at', '-pk'),
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('name', models.CharField(max_length=128)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=64)),
                ('vendor_name', models.CharField(blank=True, max_length=128)),
                ('vendor_sku', models.CharField(blank=True, db_index=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('restock_threshold', models.PositiveIntegerField(default=0, help_text='Trigger restock alerts when stock reaches this quantity (global default).')),
                ('restock_quantity', models.PositiveIntegerField(default=0, help_text='Suggested quantity to reorder when below threshold.')),
                ('is_active', models.BooleanField(default=True)),
                ('external_reference', models.CharField(blank=True, help_text='External procurement identifier or SKU.', max_length=128)),
            ],
            options={
                'verbose_name': 'Spare part',
                'verbose_name_plural': 'Spare parts',
                'ordering': ('name', 'sku'),
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SparePartCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Spare part category',
                'verbose_name_plural': 'Spare part categories',
                'ordering': ('name',),
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SparePartStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('location', models.CharField(help_text='Storage location, e.g. warehouse or vehicle identifier.', max_length=128)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0)),
                ('quantity_reserved', models.PositiveIntegerField(default=0)),
                ('reorder_point', models.PositiveIntegerField(blank=True, help_text='Override restock threshold for this location.', null=True)),
                ('reorder_quantity', models.PositiveIntegerField(blank=True, help_text='Override reorder quantity for this location.', null=True)),
                ('last_restocked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='assets.sparepart')),
            ],
            options={
                'verbose_name': 'Spare part stock',
                'verbose_name_plural': 'Spare part stocks',
                'ordering': ('part__name', 'location'),
                'unique_together': {('part', 'location')},
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='assets.sparepartcategory'),
        ),
        migrations.CreateModel(
            name='SafetyChecklistTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('name', models.CharField(max_length=128)),
                ('trigger', models.PositiveIntegerField(choices=[(1, 'Activation / pre-use'), (2, 'Maintenance release'), (3, 'Mission launch')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('require_all_pass', models.BooleanField(default=True, help_text='Require every checklist item to pass in order to use the entry.')),
                ('validity_period_hours', models.PositiveIntegerField(default=24, help_text='Maximum age (hours) of a completed checklist for transition gating.')),
                ('notes', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Restrict template to a specific asset model.', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Safety checklist template',
                'verbose_name_plural': 'Safety checklist templates',
                'ordering': ('name',),
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SafetyChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('prompt', models.CharField(max_length=256)),
                ('item_type', models.PositiveIntegerField(choices=[(1, 'Boolean (yes/no)'), (2, 'Text'), (3, 'Decimal')], default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('require_attachment', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assets.safetychecklisttemplate')),
            ],
            options={
                'verbose_name': 'Safety checklist item',
                'verbose_name_plural': 'Safety checklist items',
                'ordering': ('template', 'pk'),
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SafetyChecklistEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Draft'), (2, 'Passed'), (3, 'Failed')], default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('base_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_checklists', to='assets.baseobject')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_safety_checklists', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='assets.safetychecklisttemplate')),
            ],
            options={
                'verbose_name': 'Safety checklist entry',
                'verbose_name_plural': 'Safety checklist entries',
                'ordering': ('-completed_at', '-created'),
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MaintenancePartUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('quantity_used', models.PositiveIntegerField(default=1)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Override unit cost at time of use.', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('maintenance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_usages', to='assets.maintenancerecord')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_usages', to='assets.sparepart')),
                ('stock', models.ForeignKey(blank=True, help_text='Stock location the part was consumed from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='assets.sparepartstock')),
            ],
            options={
                'verbose_name': 'Maintenance part usage',
                'verbose_name_plural': 'Maintenance part usage',
                'ordering': ('-created',),
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AssetIncidentTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('description', models.CharField(max_length=256)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_asset_incident_tasks', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='assets.assetincident')),
            ],
            options={
                'verbose_name': 'Incident follow-up task',
                'verbose_name_plural': 'Incident follow-up tasks',
                'ordering': ('incident', 'pk'),
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SafetyChecklistResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_text', models.TextField(blank=True)),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assets.safetychecklistentry')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assets.safetychecklistitem')),
            ],
            options={
                'verbose_name': 'Safety checklist response',
                'verbose_name_plural': 'Safety checklist responses',
                'unique_together': {('entry', 'item')},
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OperatorCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('name', models.CharField(max_length=128)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Restrict certification to a specific asset model.', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operator certification',
                'verbose_name_plural': 'Operator certifications',
                'ordering': ('user', 'name'),
                'unique_together': {('user', 'name', 'content_type')},
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
    ]
