# Generated by Django 4.2.23 on 2025-10-29 21:36

from django.db import migrations, models
import django.db.models.deletion
import ralph.lib.mixins.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('assets', '0048_assetincident_sparepart_sparepartcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('name', models.CharField(max_length=128)),
                ('endpoint_type', models.PositiveIntegerField(choices=[(1, 'Webhook'), (2, 'n8n Workflow'), (3, 'Celery Task'), (4, 'ERP/Finance')], default=1)),
                ('target_url', models.CharField(blank=True, help_text='URL or dotted path depending on endpoint type.', max_length=256)),
                ('queue_name', models.CharField(blank=True, help_text='When using Celery/RQ integrations, specify queue name.', max_length=64)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('secret_token', models.CharField(blank=True, help_text='Optional token included with outbound notifications.', max_length=128)),
                ('event_filter', models.JSONField(blank=True, default=list, help_text='List of AssetEventType values; empty list means all events.')),
                ('enabled', models.BooleanField(default=True)),
                ('timeout_seconds', models.PositiveIntegerField(default=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Integration endpoint',
                'verbose_name_plural': 'Integration endpoints',
                'ordering': ('name',),
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('target_response_hours', models.DecimalField(decimal_places=2, default=4, max_digits=6)),
                ('target_resolution_hours', models.DecimalField(decimal_places=2, default=24, max_digits=6)),
                ('require_manager_ack', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Restrict SLA to assets of this model; leave blank for global.', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'SLA policy',
                'verbose_name_plural': 'SLA policies',
                'ordering': ('name',),
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='IntegrationDeliveryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('event_type', models.CharField(max_length=64)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Success'), (2, 'Failure')], default=1)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='assets.integrationendpoint')),
            ],
            options={
                'verbose_name': 'Integration delivery log',
                'verbose_name_plural': 'Integration delivery logs',
                'ordering': ('-created',),
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
    ]
