# Generated by Django 4.2.23 on 2025-10-30
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assets", "0049_integrationendpoint_slapolicy_integrationdeliverylog"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="date created")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="last modified")),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("order_type", models.PositiveIntegerField(choices=[(1, "maintenance"), (2, "repair"), (3, "inspection"), (4, "installation"), (5, "decommission"), (6, "other")], default=1)),
                ("priority", models.PositiveIntegerField(choices=[(1, "low"), (2, "normal"), (3, "high"), (4, "critical")], default=2)),
                ("status", models.PositiveIntegerField(choices=[(1, "open"), (2, "in progress"), (3, "waiting approval"), (4, "completed"), (5, "canceled")], default=1)),
                ("vendor_name", models.CharField(blank=True, max_length=128)),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("sla_target_at", models.DateTimeField(blank=True, null=True)),
                ("sla_breach_at", models.DateTimeField(blank=True, null=True)),
                ("approval_required", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("total_cost", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("notes", models.TextField(blank=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_work_orders", to=settings.AUTH_USER_MODEL)),
                ("base_object", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="work_orders", to="assets.baseobject")),
            ],
            options={
                "verbose_name": "Work order",
                "verbose_name_plural": "Work orders",
                "ordering": ("-opened_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="WorkOrderTask",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="date created")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="last modified")),
                ("name", models.CharField(max_length=128)),
                ("status", models.PositiveIntegerField(choices=[(1, "open"), (2, "in progress"), (3, "waiting approval"), (4, "completed"), (5, "canceled")], default=1)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("cost", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("notes", models.TextField(blank=True)),
                ("technician", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="work_order_tasks", to=settings.AUTH_USER_MODEL)),
                ("work_order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="assets.workorder")),
            ],
            options={
                "verbose_name": "Work order task",
                "verbose_name_plural": "Work order tasks",
                "ordering": ("work_order", "-created"),
            },
        ),
        migrations.AddField(
            model_name="maintenancerecord",
            name="work_order",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="maintenance_records", to="assets.workorder"),
        ),
    ]

