# Generated by Django 4.2.23 on 2025-10-30
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0050_workorder_and_task"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="maintenancerecord",
            index=models.Index(fields=["base_object", "status", "opened_at"], name="maint_base_stat_open"),
        ),
        migrations.AddIndex(
            model_name="maintenancerecord",
            index=models.Index(fields=["base_object", "expected_completion"], name="maint_base_expect"),
        ),
        migrations.AddIndex(
            model_name="compliancerecord",
            index=models.Index(fields=["base_object", "status"], name="compl_base_status"),
        ),
        migrations.AddIndex(
            model_name="assetutilizationsnapshot",
            index=models.Index(fields=["base_object", "date"], name="util_base_date"),
        ),
        migrations.CreateModel(
            name="AssetStatusSnapshot",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="date created")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="last modified")),
                ("date", models.DateField()),
                ("status_label", models.CharField(blank=True, max_length=64)),
                ("deployment_status_label", models.CharField(blank=True, max_length=64)),
                ("open_maintenance", models.PositiveIntegerField(default=0)),
                ("overdue_compliance", models.PositiveIntegerField(default=0)),
                ("base_object", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="status_snapshots", to="assets.baseobject")),
            ],
            options={
                "verbose_name": "Asset status snapshot",
                "verbose_name_plural": "Asset status snapshots",
            },
        ),
        migrations.AddConstraint(
            model_name="assetstatussnapshot",
            constraint=models.UniqueConstraint(fields=("base_object", "date"), name="asset_status_unique"),
        ),
        migrations.AddIndex(
            model_name="assetstatussnapshot",
            index=models.Index(fields=["base_object", "date"], name="status_base_date"),
        ),
        migrations.CreateModel(
            name="AssetCostSnapshot",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="date created")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="last modified")),
                ("month", models.DateField(help_text="Snapshot month (first day of month).")),
                ("capex", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("opex", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("maintenance", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("parts", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("fuel", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("active_hours", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("idle_hours", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("base_object", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="cost_snapshots", to="assets.baseobject")),
            ],
            options={
                "verbose_name": "Asset cost snapshot",
                "verbose_name_plural": "Asset cost snapshots",
            },
        ),
        migrations.AddConstraint(
            model_name="assetcostsnapshot",
            constraint=models.UniqueConstraint(fields=("base_object", "month"), name="asset_cost_unique"),
        ),
        migrations.AddIndex(
            model_name="assetcostsnapshot",
            index=models.Index(fields=["base_object", "month"], name="cost_base_month"),
        ),
        migrations.CreateModel(
            name="ComplianceSnapshot",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="date created")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="last modified")),
                ("date", models.DateField()),
                ("status_label", models.CharField(blank=True, max_length=32)),
                ("expires_on", models.DateField(blank=True, null=True)),
                ("risk_score", models.IntegerField(default=0)),
                ("base_object", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="compliance_snapshots", to="assets.baseobject")),
            ],
            options={
                "verbose_name": "Compliance snapshot",
                "verbose_name_plural": "Compliance snapshots",
            },
        ),
        migrations.AddConstraint(
            model_name="compliancesnapshot",
            constraint=models.UniqueConstraint(fields=("base_object", "date"), name="compliance_snapshot_unique"),
        ),
        migrations.AddIndex(
            model_name="compliancesnapshot",
            index=models.Index(fields=["base_object", "date"], name="complsnap_base_date"),
        ),
    ]

