# Generated by Django 4.2.23 on 2025-10-30
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
        ("assets", "0051_snapshots_and_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancetemplate",
            name="severity",
            field=models.PositiveIntegerField(choices=[(1, "low"), (2, "medium"), (3, "high"), (4, "critical")], default=2, help_text="Relative importance used for risk scoring."),
        ),
        migrations.AddField(
            model_name="compliancetemplate",
            name="owner_user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="owned_compliance_templates", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="compliancetemplate",
            name="owner_team",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="owned_compliance_templates", to="accounts.team"),
        ),
        migrations.AddField(
            model_name="compliancetemplate",
            name="required_documents",
            field=models.PositiveIntegerField(default=0, help_text="Number of evidence documents required for compliance."),
        ),
        migrations.CreateModel(
            name="ReportConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="date created")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="last modified")),
                ("name", models.CharField(max_length=128)),
                ("endpoint", models.CharField(help_text="Endpoint key: inventory, utilization, maintenance-compliance, lifecycle, financial, resources, dashboard-ops, dashboard-compliance, dashboard-finance", max_length=64)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("export_format", models.CharField(default="csv", max_length=8)),
                ("recipients", models.TextField(help_text="Comma or newline separated email recipients.")),
                ("is_active", models.BooleanField(default=True)),
                ("schedule_interval_seconds", models.PositiveIntegerField(default=0, help_text="Run every N seconds (0 disables scheduling).")),
                ("initial_delay_seconds", models.PositiveIntegerField(default=0)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Saved report configuration",
                "verbose_name_plural": "Saved report configurations",
                "ordering": ("name",),
            },
        ),
    ]

