# Generated by Django 4.2.23 on 2025-11-01
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0052_compliance_template_and_reportconfig"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="baseobject",
            index=models.Index(fields=["content_type"], name="baseobj_ct_idx"),
        ),
    ]

