services:
  assets-web:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: docker/Dockerfile-service
    depends_on:
      - assets-db
      - assets-redis
    restart: unless-stopped
    ports:
      - "8005:8005"
    environment:
        DATABASE_NAME: ralph_ng
        DATABASE_TEST_NAME: test_ralph_ng
        DATABASE_USER: ralph_ng
        DATABASE_PASSWORD: ralph_ng
        DATABASE_HOST: assets-db
        DATABASE_PORT: 3306
        DATABASE_ENGINE: django.db.backends.mysql
        REDIS_HOST: assets-redis
        REDIS_PASSWORD: ""
        REDIS_PORT: 6379
        REDIS_DB: 0
        RALPH_PORT: 8005

  assets-db:
    platform: linux/amd64
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ralph_ng
      MYSQL_ROOT_PASSWORD: ralph_ng
      MYSQL_USER: ralph_ng
      MYSQL_PASSWORD: ralph_ng
    volumes:
      - ralph_dbdata:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped

  assets-redis:
    image: redis:7.0.11
    restart: unless-stopped

  assets-inkpy:
    build:
      context: ../
      dockerfile: docker/Dockerfile-inkpy
    platform: linux/amd64
    environment:
        REDIS_HOST: assets-redis
        REDIS_PASSWORD: ""
        REDIS_PORT: 6379
        REDIS_DB: 0
    restart: unless-stopped

  assets-nginx:
    build:
      context: ../
      dockerfile: docker/Dockerfile-local-dev-static
    ports:
      - "18080:80"
    volumes:
      - ../src/ralph:/opt/media
      - ../src/ralph/static:/opt/static
    restart: unless-stopped
volumes:
  ralph_dbdata:
