# Generated by Django 4.2.23 on 2025-10-28 16:58

from django.db import migrations, models
import django.db.models.manager
import ralph.lib.transitions.fields

from ralph.lib.transitions.migration import TransitionActionMigration


def _get_actions(content_type, action_names, ActionModel):
    actions = []
    for action_name in action_names:
        action, _ = ActionModel.objects.get_or_create(name=action_name)
        action.content_type.add(content_type)
        actions.append(action)
    return actions


def create_drone_transitions(apps, schema_editor):
    from ralph.drones.models import DroneAsset, DroneAssetStatus

    Transition = apps.get_model("transitions", "Transition")
    TransitionModel = apps.get_model("transitions", "TransitionModel")
    Action = apps.get_model("transitions", "Action")

    from django.contrib.contenttypes.models import ContentType as DjangoContentType

    ContentTypeModel = apps.get_model("contenttypes", "ContentType")
    ct_id = DjangoContentType.objects.get_for_model(DroneAsset).pk
    content_type = ContentTypeModel.objects.get(pk=ct_id)
    transition_model, _ = TransitionModel.objects.get_or_create(
        content_type=content_type,
        field_name="status",
    )

    transitions = [
        (
            "Activate drone",
            [DroneAssetStatus.new.id],
            DroneAssetStatus.active.id,
            ["activate_drone_asset"],
        ),
        (
            "Begin maintenance",
            [DroneAssetStatus.active.id, DroneAssetStatus.grounded.id],
            DroneAssetStatus.under_maintenance.id,
            ["start_drone_maintenance"],
        ),
        (
            "Complete maintenance",
            [DroneAssetStatus.under_maintenance.id],
            DroneAssetStatus.active.id,
            ["complete_drone_maintenance"],
        ),
        (
            "Ground drone",
            [DroneAssetStatus.active.id],
            DroneAssetStatus.grounded.id,
            ["ground_drone_asset"],
        ),
        (
            "Return to service",
            [DroneAssetStatus.grounded.id, DroneAssetStatus.under_maintenance.id],
            DroneAssetStatus.active.id,
            ["return_drone_to_service"],
        ),
        (
            "Retire drone",
            [
                DroneAssetStatus.new.id,
                DroneAssetStatus.active.id,
                DroneAssetStatus.under_maintenance.id,
                DroneAssetStatus.grounded.id,
            ],
            DroneAssetStatus.retired.id,
            ["retire_drone_asset"],
        ),
    ]

    for name, source, target, action_names in transitions:
        transition, _ = Transition.objects.update_or_create(
            model=transition_model,
            name=name,
            defaults={
                "source": source,
                "target": str(target),
                "run_asynchronously": False,
                "async_service_name": None,
            },
        )
        actions = _get_actions(content_type, action_names, Action)
        transition.actions.set(actions)


def remove_drone_transitions(apps, schema_editor):
    from ralph.drones.models import DroneAsset

    Transition = apps.get_model("transitions", "Transition")
    TransitionModel = apps.get_model("transitions", "TransitionModel")

    from django.contrib.contenttypes.models import ContentType as DjangoContentType

    ContentTypeModel = apps.get_model("contenttypes", "ContentType")
    ct_id = DjangoContentType.objects.get_for_model(DroneAsset).pk
    content_type = ContentTypeModel.objects.get(pk=ct_id)
    try:
        transition_model = TransitionModel.objects.get(
            content_type=content_type,
            field_name="status",
        )
    except TransitionModel.DoesNotExist:
        return

    Transition.objects.filter(
        model=transition_model,
        name__in=[
            "Activate drone",
            "Begin maintenance",
            "Complete maintenance",
            "Ground drone",
            "Return to service",
            "Retire drone",
        ],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_droneasset'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='droneasset',
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='drone',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='droneasset',
            name='status',
            field=ralph.lib.transitions.fields.TransitionField(choices=[(1, 'new'), (2, 'active'), (3, 'under maintenance'), (4, 'grounded'), (5, 'retired')], default=1),
        ),
        migrations.AlterField(
            model_name='droneassignment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='droneflightlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dronemaintenancelog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dronestatuslog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        TransitionActionMigration(),
        migrations.RunPython(create_drone_transitions, remove_drone_transitions),
    ]
