# Generated by Django 4.2.23 on 2025-10-28 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_alter_droneasset_managers_alter_drone_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneasset',
            name='battery_health_threshold_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='battery health threshold (%)'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='current_mission',
            field=models.CharField(blank=True, max_length=128, verbose_name='current mission'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='last_service_date',
            field=models.DateField(blank=True, null=True, verbose_name='last service date'),
        ),
    ]
