# Generated by Django 4.2.23 on 2025-10-29 02:56

from django.db import migrations, models
import django.db.models.manager
import ralph.drones.models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0004_droneasset_battery_health_threshold_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDroneAsset',
            fields=[
            ],
            options={
                'verbose_name': 'Delivery drone',
                'verbose_name_plural': 'Delivery drones',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ralph.drones.models.DroneAssetMissionProxyMixin, 'drones.droneasset'),
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='InspectionDroneAsset',
            fields=[
            ],
            options={
                'verbose_name': 'Inspection & maintenance drone',
                'verbose_name_plural': 'Inspection & maintenance drones',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ralph.drones.models.DroneAssetMissionProxyMixin, 'drones.droneasset'),
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SurveillanceDroneAsset',
            fields=[
            ],
            options={
                'verbose_name': 'Surveillance & security drone',
                'verbose_name_plural': 'Surveillance & security drones',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ralph.drones.models.DroneAssetMissionProxyMixin, 'drones.droneasset'),
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SurveyDroneAsset',
            fields=[
            ],
            options={
                'verbose_name': 'Survey & mapping drone',
                'verbose_name_plural': 'Survey & mapping drones',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ralph.drones.models.DroneAssetMissionProxyMixin, 'drones.droneasset'),
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingDroneAsset',
            fields=[
            ],
            options={
                'verbose_name': 'Training & testing drone',
                'verbose_name_plural': 'Training & testing drones',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ralph.drones.models.DroneAssetMissionProxyMixin, 'drones.droneasset'),
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='droneasset',
            name='mission_profile',
            field=models.CharField(choices=[('survey', 'Survey & mapping'), ('surveillance', 'Surveillance & security'), ('delivery', 'Delivery & logistics'), ('inspection', 'Inspection & maintenance'), ('training', 'Training & testing'), ('multi_role', 'Multi-role / other')], default='multi_role', max_length=32, verbose_name='mission profile'),
        ),
    ]
