# Generated by Django 4.2.23 on 2025-10-29 18:11

import django.core.validators
from django.db import migrations, models
import ralph.lib.mixins.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0005_deliverydroneasset_inspectiondroneasset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneasset',
            name='airframe_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='airframe weight (kg)'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='airworthiness_certificate_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='airworthiness certificate ID'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='airworthiness_expires_on',
            field=models.DateField(blank=True, null=True, verbose_name='airworthiness expiry'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='battery_cycle_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='battery cycle count'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='battery_low_threshold_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='low battery threshold (%)'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='communication_link_type',
            field=models.CharField(blank=True, max_length=64, verbose_name='communication link type'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='failsafe_behavior',
            field=models.CharField(blank=True, max_length=128, verbose_name='failsafe behavior'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='home_location_description',
            field=models.CharField(blank=True, max_length=128, verbose_name='home location'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='insurance expiry'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='insurance policy number'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=128, verbose_name='insurance provider'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='last_inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='last inspection date'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='manufacture_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='manufacture year'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=128, verbose_name='manufacturer'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='max_endurance_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='maximum endurance (minutes)'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='max_payload_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='maximum payload (kg)'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='max_range_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='maximum range (km)'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='mission_payload_description',
            field=models.CharField(blank=True, max_length=256, verbose_name='payload description'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='next_inspection_due',
            field=models.DateField(blank=True, null=True, verbose_name='next inspection due'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='operator_certificate_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='operator certificate number'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='payload_mounting',
            field=models.CharField(blank=True, max_length=128, verbose_name='payload mount'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='payload_power_requirements',
            field=models.CharField(blank=True, max_length=128, verbose_name='payload power requirements'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='pilot_license_required',
            field=models.CharField(blank=True, max_length=128, verbose_name='pilot license requirement'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='registration_authority',
            field=models.CharField(blank=True, max_length=128, verbose_name='registration authority'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='registration_expires_on',
            field=models.DateField(blank=True, null=True, verbose_name='registration expiry'),
        ),
        migrations.AddField(
            model_name='droneasset',
            name='registration_id',
            field=ralph.lib.mixins.fields.NullableCharField(blank=True, max_length=64, null=True, unique=True, verbose_name='registration ID'),
        ),
    ]
