# Generated by Django 4.2.23 on 2025-10-12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ralph.lib.mixins.fields


class Migration(migrations.Migration):
    dependencies = [
        ("back_office", "0027_alter_backofficeasset_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DisasterReliefVehicle",
            fields=[
                (
                    "backofficeasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="back_office.backofficeasset",
                    ),
                ),
                (
                    "license_plate",
                    ralph.lib.mixins.fields.NullableCharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="license plate",
                    ),
                ),
                (
                    "mileage",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Recorded mileage in kilometers.",
                        null=True,
                        verbose_name="mileage",
                    ),
                ),
                (
                    "hours_used",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Cumulative operating hours.",
                        null=True,
                        verbose_name="hours used",
                    ),
                ),
                (
                    "power_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rated power output (for example in kW or kVA).",
                        max_digits=10,
                        null=True,
                        verbose_name="power rating",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disaster-relief vehicle",
                "verbose_name_plural": "Disaster-relief vehicles",
            },
            bases=("back_office.backofficeasset",),
        ),
        migrations.CreateModel(
            name="DisasterReliefHeavyEquipment",
            fields=[
                (
                    "backofficeasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="back_office.backofficeasset",
                    ),
                ),
                (
                    "license_plate",
                    ralph.lib.mixins.fields.NullableCharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="license plate",
                    ),
                ),
                (
                    "mileage",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Recorded mileage in kilometers.",
                        null=True,
                        verbose_name="mileage",
                    ),
                ),
                (
                    "hours_used",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Cumulative operating hours.",
                        null=True,
                        verbose_name="hours used",
                    ),
                ),
                (
                    "power_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rated power output (for example in kW or kVA).",
                        max_digits=10,
                        null=True,
                        verbose_name="power rating",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disaster-relief heavy equipment",
                "verbose_name_plural": "Disaster-relief heavy equipment",
            },
            bases=("back_office.backofficeasset",),
        ),
        migrations.CreateModel(
            name="DisasterReliefTrailer",
            fields=[
                (
                    "backofficeasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="back_office.backofficeasset",
                    ),
                ),
                (
                    "license_plate",
                    ralph.lib.mixins.fields.NullableCharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="license plate",
                    ),
                ),
                (
                    "mileage",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Recorded mileage in kilometers.",
                        null=True,
                        verbose_name="mileage",
                    ),
                ),
                (
                    "hours_used",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Cumulative operating hours.",
                        null=True,
                        verbose_name="hours used",
                    ),
                ),
                (
                    "power_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rated power output (for example in kW or kVA).",
                        max_digits=10,
                        null=True,
                        verbose_name="power rating",
                    ),
                ),
                (
                    "trailer_type",
                    ralph.lib.mixins.fields.NullableCharField(
                        blank=True,
                        choices=[
                            ("flatbed", "Flatbed"),
                            ("enclosed", "Enclosed"),
                            ("utility", "Utility"),
                            ("tanker", "Tanker"),
                            ("refrigerated", "Refrigerated"),
                            ("other", "Other"),
                        ],
                        max_length=64,
                        null=True,
                        verbose_name="trailer type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disaster-relief trailer",
                "verbose_name_plural": "Disaster-relief trailers",
            },
            bases=("back_office.backofficeasset",),
        ),
        migrations.CreateModel(
            name="MaintenanceLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="date created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="last modified",
                    ),
                ),
                ("service_date", models.DateField(verbose_name="service date")),
                (
                    "description",
                    models.TextField(verbose_name="work description"),
                ),
                (
                    "next_due_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional reminder for the next planned maintenance.",
                        null=True,
                        verbose_name="next due date",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_logs",
                        to="back_office.backofficeasset",
                        verbose_name="asset",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="performed by",
                    ),
                ),
            ],
            options={
                "verbose_name": "maintenance log",
                "verbose_name_plural": "maintenance logs",
                "ordering": ["-service_date", "-created"],
            },
        ),
        migrations.CreateModel(
            name="UsageLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="date created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="last modified",
                    ),
                ),
                ("reading_date", models.DateField(verbose_name="reading date")),
                (
                    "mileage_delta",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Mileage added since last reading (in kilometers).",
                        null=True,
                        verbose_name="mileage increment",
                    ),
                ),
                (
                    "hours_delta",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Hours added since last reading.",
                        null=True,
                        verbose_name="hours increment",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="back_office.backofficeasset",
                        verbose_name="asset",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recorded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "usage log",
                "verbose_name_plural": "usage logs",
                "ordering": ["-reading_date", "-created"],
            },
        ),
    ]
