# Generated by Django 4.2.23 on 2025-10-21 16:17

from django.db import migrations
import django.db.models.manager
import ralph.lib.mixins.fields


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0028_disaster_relief_assets'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='disasterreliefheavyequipment',
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='disasterrelieftrailer',
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='disasterreliefvehicle',
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='disasterrelieftrailer',
            name='trailer_type',
            field=ralph.lib.mixins.fields.NullableCharField(blank=True, choices=[(1, 'Flatbed'), (2, 'Enclosed'), (3, 'Utility'), (4, 'Tanker'), (5, 'Refrigerated'), (6, 'Other')], max_length=64, null=True, verbose_name='trailer type'),
        ),
    ]
