# Generated by Django 4.2.23 on 2025-10-28 16:58

from django.db import migrations, models
import django.db.models.manager
import ralph.lib.transitions.fields

from ralph.lib.transitions.migration import TransitionActionMigration


def _get_actions(content_type, action_names, ActionModel):
    actions = []
    for action_name in action_names:
        action, _ = ActionModel.objects.get_or_create(name=action_name)
        action.content_type.add(content_type)
        actions.append(action)
    return actions


def create_fleet_transitions(apps, schema_editor):
    from ralph.fleet.models import FleetAsset, FleetAssetStatus

    Transition = apps.get_model("transitions", "Transition")
    TransitionModel = apps.get_model("transitions", "TransitionModel")
    Action = apps.get_model("transitions", "Action")

    from django.contrib.contenttypes.models import ContentType as DjangoContentType

    ContentTypeModel = apps.get_model("contenttypes", "ContentType")
    ct_id = DjangoContentType.objects.get_for_model(FleetAsset).pk
    content_type = ContentTypeModel.objects.get(pk=ct_id)
    transition_model, _ = TransitionModel.objects.get_or_create(
        content_type=content_type,
        field_name="status",
    )

    transitions = [
        (
            "Activate asset",
            [FleetAssetStatus.new.id],
            FleetAssetStatus.in_use.id,
            ["activate_fleet_asset"],
        ),
        (
            "Begin maintenance",
            [FleetAssetStatus.in_use.id, FleetAssetStatus.damaged.id],
            FleetAssetStatus.under_maintenance.id,
            ["start_fleet_maintenance"],
        ),
        (
            "Complete maintenance",
            [FleetAssetStatus.under_maintenance.id],
            FleetAssetStatus.in_use.id,
            ["complete_fleet_maintenance"],
        ),
        (
            "Report damage",
            [FleetAssetStatus.in_use.id],
            FleetAssetStatus.damaged.id,
            ["flag_fleet_damage"],
        ),
        (
            "Retire asset",
            [
                FleetAssetStatus.new.id,
                FleetAssetStatus.in_use.id,
                FleetAssetStatus.under_maintenance.id,
                FleetAssetStatus.damaged.id,
            ],
            FleetAssetStatus.retired.id,
            ["retire_fleet_asset"],
        ),
    ]

    for name, source, target, action_names in transitions:
        transition, _ = Transition.objects.update_or_create(
            model=transition_model,
            name=name,
            defaults={
                "source": source,
                "target": str(target),
                "run_asynchronously": False,
                "async_service_name": None,
            },
        )
        actions = _get_actions(content_type, action_names, Action)
        transition.actions.set(actions)


def remove_fleet_transitions(apps, schema_editor):
    from ralph.fleet.models import FleetAsset

    Transition = apps.get_model("transitions", "Transition")
    TransitionModel = apps.get_model("transitions", "TransitionModel")

    from django.contrib.contenttypes.models import ContentType as DjangoContentType

    ContentTypeModel = apps.get_model("contenttypes", "ContentType")
    ct_id = DjangoContentType.objects.get_for_model(FleetAsset).pk
    content_type = ContentTypeModel.objects.get(pk=ct_id)
    try:
        transition_model = TransitionModel.objects.get(
            content_type=content_type,
            field_name="status",
        )
    except TransitionModel.DoesNotExist:
        return

    Transition.objects.filter(
        model=transition_model,
        name__in=[
            "Activate asset",
            "Begin maintenance",
            "Complete maintenance",
            "Report damage",
            "Retire asset",
        ],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_fleetasset'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='fleetasset',
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='fleetasset',
            name='status',
            field=ralph.lib.transitions.fields.TransitionField(choices=[(1, 'new'), (2, 'in use'), (3, 'under maintenance'), (4, 'damaged'), (5, 'retired')], default=1),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicleassignment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenancelog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehiclestatuslog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicleusagelog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        TransitionActionMigration(),
        migrations.RunPython(create_fleet_transitions, remove_fleet_transitions),
    ]
