# Generated by Django 4.2.23 on 2025-10-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_fleetasset_managers_alter_fleetasset_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetasset',
            name='inspection_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='inspection due date'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='insurance expiry'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='registration_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='registration expiry'),
        ),
    ]
