# Generated by Django 4.2.23 on 2025-10-29 18:11

import django.core.validators
from django.db import migrations, models
import django.db.models.manager
import ralph.fleet.models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_fleetasset_inspection_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetEmergencyVehicle',
            fields=[
            ],
            options={
                'verbose_name': 'Emergency response vehicle',
                'verbose_name_plural': 'Emergency response vehicles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ralph.fleet.models.FleetAssetGroupProxyMixin, 'fleet.fleetasset'),
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FleetLightVehicle',
            fields=[
            ],
            options={
                'verbose_name': 'Light vehicle',
                'verbose_name_plural': 'Light vehicles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ralph.fleet.models.FleetAssetGroupProxyMixin, 'fleet.fleetasset'),
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FleetPassengerVehicle',
            fields=[
            ],
            options={
                'verbose_name': 'Passenger transport vehicle',
                'verbose_name_plural': 'Passenger transport vehicles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ralph.fleet.models.FleetAssetGroupProxyMixin, 'fleet.fleetasset'),
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FleetTruckHauler',
            fields=[
            ],
            options={
                'verbose_name': 'Truck or hauler',
                'verbose_name_plural': 'Trucks & haulers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ralph.fleet.models.FleetAssetGroupProxyMixin, 'fleet.fleetasset'),
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FleetUtilityVehicle',
            fields=[
            ],
            options={
                'verbose_name': 'Utility vehicle',
                'verbose_name_plural': 'Utility vehicles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ralph.fleet.models.FleetAssetGroupProxyMixin, 'fleet.fleetasset'),
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='body_style',
            field=models.CharField(blank=True, max_length=64, verbose_name='body style'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='color',
            field=models.CharField(blank=True, max_length=32, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='drivetrain',
            field=models.CharField(blank=True, max_length=32, verbose_name='drivetrain'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='emergency_equipment_inventory',
            field=models.TextField(blank=True, verbose_name='emergency equipment inventory'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='emissions_class',
            field=models.CharField(blank=True, max_length=32, verbose_name='emissions class'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='engine_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='engine hours'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='fuel_card_identifier',
            field=models.CharField(blank=True, max_length=32, verbose_name='fuel card ID'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='fuel_level_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='fuel level (%)'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='gross_vehicle_weight_rating_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='GVWR (kg)'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='insurance policy number'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=64, verbose_name='insurance provider'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='last_known_heading_deg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='last known heading (deg)'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='last_known_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='last known latitude'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='last_known_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='last known longitude'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='last_known_speed_kmh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='last known speed (km/h)'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='last_telematics_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last telematics update'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='last_telematics_status',
            field=models.CharField(blank=True, max_length=32, verbose_name='last telematics status'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='make',
            field=models.CharField(blank=True, max_length=64, verbose_name='make'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='manufacture_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='manufacture year'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='registration_authority',
            field=models.CharField(blank=True, max_length=64, verbose_name='registration authority'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='registration_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='registration number'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='registration_state',
            field=models.CharField(blank=True, max_length=32, verbose_name='registration state / region'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='roadworthiness_certificate_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='roadworthiness certificate expiry'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='seating_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='seating capacity'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='telematics_device_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='telematics device ID'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='telematics_provider',
            field=models.CharField(blank=True, max_length=64, verbose_name='telematics provider'),
        ),
        migrations.AddField(
            model_name='fleetasset',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=64, verbose_name='vehicle model'),
        ),
        migrations.AlterField(
            model_name='fleetasset',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('van', 'Van'), ('suv', 'SUV'), ('heavy', 'Heavy equipment'), ('ambulance', 'Ambulance'), ('fire', 'Fire / Rescue vehicle'), ('command', 'Command / Support unit'), ('bus', 'Bus / Shuttle'), ('other', 'Other')], default='other', max_length=32, verbose_name='vehicle type'),
        ),
    ]
