# Generated by Django 4.2.23 on 2025-10-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0010_alter_licence_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='asset_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'back office'), (2, 'data center'), (3, 'part'), (4, 'all'), (5, 'fleet'), (6, 'drone'), (7, 'sensor'), (8, 'heavy equipment')], default=4),
        ),
    ]
