# Generated by Django 4.2.23 on 2025-10-28 16:58

from django.db import migrations, models
import django.db.models.manager
import ralph.lib.transitions.fields

from ralph.lib.transitions.migration import TransitionActionMigration


def _get_actions(content_type, action_names, ActionModel):
    actions = []
    for action_name in action_names:
        action, _ = ActionModel.objects.get_or_create(name=action_name)
        action.content_type.add(content_type)
        actions.append(action)
    return actions


def create_sensor_transitions(apps, schema_editor):
    from ralph.sensors.models import SensorAsset, SensorAssetStatus

    Transition = apps.get_model("transitions", "Transition")
    TransitionModel = apps.get_model("transitions", "TransitionModel")
    Action = apps.get_model("transitions", "Action")

    from django.contrib.contenttypes.models import ContentType as DjangoContentType

    ContentTypeModel = apps.get_model("contenttypes", "ContentType")
    ct_id = DjangoContentType.objects.get_for_model(SensorAsset).pk
    content_type = ContentTypeModel.objects.get(pk=ct_id)
    transition_model, _ = TransitionModel.objects.get_or_create(
        content_type=content_type,
        field_name="status",
    )

    transitions = [
        (
            "Activate sensor",
            [SensorAssetStatus.new.id],
            SensorAssetStatus.active.id,
            ["activate_sensor_asset"],
        ),
        (
            "Begin maintenance",
            [SensorAssetStatus.active.id, SensorAssetStatus.faulty.id],
            SensorAssetStatus.under_maintenance.id,
            ["start_sensor_maintenance"],
        ),
        (
            "Complete maintenance",
            [SensorAssetStatus.under_maintenance.id],
            SensorAssetStatus.active.id,
            ["complete_sensor_maintenance"],
        ),
        (
            "Mark faulty",
            [SensorAssetStatus.active.id],
            SensorAssetStatus.faulty.id,
            ["mark_sensor_faulty"],
        ),
        (
            "Restore sensor",
            [SensorAssetStatus.faulty.id],
            SensorAssetStatus.active.id,
            ["restore_sensor_asset"],
        ),
        (
            "Retire sensor",
            [
                SensorAssetStatus.new.id,
                SensorAssetStatus.active.id,
                SensorAssetStatus.under_maintenance.id,
                SensorAssetStatus.faulty.id,
            ],
            SensorAssetStatus.retired.id,
            ["retire_sensor_asset"],
        ),
    ]

    for name, source, target, action_names in transitions:
        transition, _ = Transition.objects.update_or_create(
            model=transition_model,
            name=name,
            defaults={
                "source": source,
                "target": str(target),
                "run_asynchronously": False,
                "async_service_name": None,
            },
        )
        actions = _get_actions(content_type, action_names, Action)
        transition.actions.set(actions)


def remove_sensor_transitions(apps, schema_editor):
    from ralph.sensors.models import SensorAsset

    Transition = apps.get_model("transitions", "Transition")
    TransitionModel = apps.get_model("transitions", "TransitionModel")

    from django.contrib.contenttypes.models import ContentType as DjangoContentType

    ContentTypeModel = apps.get_model("contenttypes", "ContentType")
    ct_id = DjangoContentType.objects.get_for_model(SensorAsset).pk
    content_type = ContentTypeModel.objects.get(pk=ct_id)
    try:
        transition_model = TransitionModel.objects.get(
            content_type=content_type,
            field_name="status",
        )
    except TransitionModel.DoesNotExist:
        return

    Transition.objects.filter(
        model=transition_model,
        name__in=[
            "Activate sensor",
            "Begin maintenance",
            "Complete maintenance",
            "Mark faulty",
            "Restore sensor",
            "Retire sensor",
        ],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_sensorasset'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sensorasset',
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='sensor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sensorasset',
            name='status',
            field=ralph.lib.transitions.fields.TransitionField(choices=[(1, 'new'), (2, 'active'), (3, 'under maintenance'), (4, 'faulty'), (5, 'retired')], default=1),
        ),
        migrations.AlterField(
            model_name='sensorassignment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sensormaintenancelog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sensorstatuslog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sensoruptimelog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        TransitionActionMigration(),
        migrations.RunPython(create_sensor_transitions, remove_sensor_transitions),
    ]
