# Generated by Django 4.2.23 on 2025-10-28 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_sensorasset_managers_alter_sensor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorasset',
            name='battery_level_threshold_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='battery threshold (%)'),
        ),
    ]
