# Generated by Django 4.2.23 on 2025-10-29 02:56

from django.db import migrations, models
import django.db.models.manager
import ralph.sensors.models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_sensorasset_battery_level_threshold_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalSensorAsset',
            fields=[
            ],
            options={
                'verbose_name': 'Environmental sensor',
                'verbose_name_plural': 'Environmental sensors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ralph.sensors.models.SensorAssetCategoryProxyMixin, 'sensors.sensorasset'),
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='InfrastructureSensorAsset',
            fields=[
            ],
            options={
                'verbose_name': 'Infrastructure sensor',
                'verbose_name_plural': 'Infrastructure sensors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ralph.sensors.models.SensorAssetCategoryProxyMixin, 'sensors.sensorasset'),
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsSensorAsset',
            fields=[
            ],
            options={
                'verbose_name': 'Logistics & tracking sensor',
                'verbose_name_plural': 'Logistics & tracking sensors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ralph.sensors.models.SensorAssetCategoryProxyMixin, 'sensors.sensorasset'),
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SecuritySensorAsset',
            fields=[
            ],
            options={
                'verbose_name': 'Security sensor',
                'verbose_name_plural': 'Security sensors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ralph.sensors.models.SensorAssetCategoryProxyMixin, 'sensors.sensorasset'),
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WearableSensorAsset',
            fields=[
            ],
            options={
                'verbose_name': 'Wearable support sensor',
                'verbose_name_plural': 'Wearable support sensors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ralph.sensors.models.SensorAssetCategoryProxyMixin, 'sensors.sensorasset'),
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='sensorasset',
            name='category',
            field=models.CharField(choices=[(1, 'Environmental monitoring'), (2, 'Security & surveillance'), (3, 'Infrastructure & utilities'), (4, 'Logistics & asset tracking'), (5, 'Wearable / personnel support'), (6, 'Other sensors')], default=6, max_length=32, verbose_name='category'),
        ),
    ]
