# Generated by Django 4.2.23 on 2025-10-29 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0045_telemetryreading_deploymententry_compliancerecord'),
        ('sensors', '0005_environmentalsensorasset_infrastructuresensorasset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorasset',
            name='communication_protocol',
            field=models.CharField(blank=True, max_length=64, verbose_name='communication protocol'),
        ),
        migrations.AddField(
            model_name='sensorasset',
            name='expected_update_interval_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='expected update interval (s)'),
        ),
        migrations.AddField(
            model_name='sensorasset',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=64, verbose_name='firmware version'),
        ),
        migrations.AddField(
            model_name='sensorasset',
            name='hardware_revision',
            field=models.CharField(blank=True, max_length=32, verbose_name='hardware revision'),
        ),
        migrations.AddField(
            model_name='sensorasset',
            name='installation_site',
            field=models.CharField(blank=True, max_length=128, verbose_name='installation site reference'),
        ),
        migrations.AddField(
            model_name='sensorasset',
            name='maintenance_contact',
            field=models.CharField(blank=True, max_length=128, verbose_name='maintenance contact'),
        ),
        migrations.AddField(
            model_name='sensorasset',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=128, verbose_name='manufacturer'),
        ),
        migrations.AddField(
            model_name='sensorasset',
            name='measurement_unit',
            field=models.CharField(blank=True, max_length=32, verbose_name='measurement unit'),
        ),
        migrations.AddField(
            model_name='sensorasset',
            name='parent_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_sensors', to='assets.baseobject', verbose_name='attached to asset'),
        ),
        migrations.AddField(
            model_name='sensorasset',
            name='power_source',
            field=models.CharField(blank=True, max_length=64, verbose_name='power source'),
        ),
    ]
