# Generated by Django 4.2.23 on 2025-10-30 04:41

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heavy_equipment', '0005_delete_heavyequipmentpowergeneration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailerAsset',
            fields=[
                ('heavyequipmentasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='heavy_equipment.heavyequipmentasset')),
                ('trailer_subtype', models.CharField(choices=[('command', 'Mobile command trailer'), ('office', 'Office trailer'), ('restroom', 'Restroom trailer'), ('shower', 'Shower trailer'), ('laundry', 'Laundry trailer'), ('sleeping', 'Sleeping quarters'), ('medical', 'Medical/mobile clinic'), ('communications', 'Communications/Fiber trailer'), ('water', 'Water tank trailer'), ('storage', 'Storage / logistics trailer'), ('specialty', 'Specialty trailer')], default='specialty', max_length=32)),
                ('occupancy_capacity', models.PositiveIntegerField(blank=True, help_text='Total personnel capacity for this trailer.', null=True)),
                ('fixtures', models.PositiveIntegerField(blank=True, help_text='Number of restroom/shower fixtures (if applicable).', null=True)),
                ('occupancy_status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('out_of_service', 'Out of service'), ('cleaning', 'Servicing / cleaning')], default='available', max_length=32)),
                ('has_climate_control', models.BooleanField(default=False)),
                ('has_onboard_generator', models.BooleanField(default=False)),
                ('last_service_visit', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Trailer',
                'verbose_name_plural': 'Trailers',
            },
            bases=('heavy_equipment.heavyequipmentasset',),
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
