# Generated by Django 4.2.23 on 2025-10-30 04:41

from django.db import migrations


TRAILER_EQUIPMENT_TYPES = ("trailer", "tank")
WATER_SUBTYPE = "water"
DEFAULT_SUBTYPE = "specialty"


def create_trailer_records(apps, schema_editor):
    HeavyEquipmentAsset = apps.get_model("heavy_equipment", "HeavyEquipmentAsset")
    TrailerAsset = apps.get_model("trailers", "TrailerAsset")

    trailer_manager = TrailerAsset._base_manager
    existing_ids = set(
        trailer_manager.values_list("heavyequipmentasset_ptr_id", flat=True)
    )
    candidates = HeavyEquipmentAsset._base_manager.filter(
        equipment_type__in=TRAILER_EQUIPMENT_TYPES
    )
    bulk = []
    for asset in candidates:
        if asset.pk in existing_ids:
            continue
        subtype = WATER_SUBTYPE if asset.equipment_type == "tank" else DEFAULT_SUBTYPE
        bulk.append(
            TrailerAsset(
                heavyequipmentasset_ptr_id=asset.pk,
                trailer_subtype=subtype,
            )
        )
    if bulk:
            trailer_manager.bulk_create(bulk, ignore_conflicts=True)


def remove_trailer_records(apps, schema_editor):
    TrailerAsset = apps.get_model("trailers", "TrailerAsset")
    TrailerAsset._base_manager.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("trailers", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_trailer_records, remove_trailer_records),
    ]
