# Generated by Django 4.2.23 on 2025-10-30 05:25

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trailers", "0002_reclassify_trailers"),
    ]

    operations = [
        migrations.AddField(
            model_name="trailerasset",
            name="occupancy_last_reported_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the last occupancy telemetry reading.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trailerasset",
            name="occupancy_level_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Most recent occupancy reading (percentage) captured from telemetry or inspections.",
                max_digits=5,
                null=True,
                validators=[MinValueValidator(0), MaxValueValidator(100)],
            ),
        ),
    ]
